### ISSUE TITLE
fileTreeExtractor.ignoredItems does not ignore nested directories

### ISSUE THREAD

**Issue by Bit-Blazer** [fuzionix/vscode-file-tree#2]
### `fileTreeExtractor.ignoredItems` does not ignore nested directories (e.g., `venv`)

**Description**:  
The `fileTreeExtractor.ignoredItems` setting does not appear to ignore nested directories when generating the file tree. For example, adding `"venv"` to the `fileTreeExtractor.ignoredItems` list does not exclude the `venv` directory located inside the `backend` folder. However, specifying `backend` (a top-level directory) works as expected.

---

**Steps to Reproduce**:

1. Create a project with the following directory structure:

```

Project/
├── backend/
│ ├── venv/
│ └── app.py
└── README.md

```

2. Update the `fileTreeExtractor.ignoredItems` setting in `settings.json` to include `"venv"`:

```json
{
  "fileTreeExtractor.ignoredItems": [".git", "node_modules", "venv"]
}
```

3. Right-click the root folder in VS Code Explorer and select **"Copy File Tree"**.

---

**Expected Behavior**:  
The `venv` directory (and its contents) should be excluded from the copied file tree output.

---

**Actual Behavior**:  
The `venv` directory is still included in the generated file tree, despite being listed in `fileTreeExtractor.ignoredItems`.

---

**Workarounds**:

1. **Ignore Parent Folder**:  
   One way to exclude the `venv` directory is to ignore its parent folder (`backend`). However, this is not feasible for most use cases, as it excludes more than intended.

2. **Use the `fileTreeExtractor.ignoredBy` Setting**:  
   Update the `fileTreeExtractor.ignoredBy` setting to `"gitignore"` or `"both"`, and then add `venv` to the `.gitignore` file. This ensures that the `venv` directory is excluded.  
   Example configuration in `settings.json`:
   ```json
   {
     "fileTreeExtractor.ignoredBy": "both"
   }
   ```
   Example `.gitignore` file:
   ```
   venv/
   ```

---

**Environment**:

- **VS Code Version**: 1.95.3  
- **File Tree Extractor Version**: v1.0.2  
- **Operating System**: Windows 11

**Comment by fuzionix** [comment]
The issue has been resolved in the latest version.

The `fileTreeExtractor.ignoredItems` setting now supports:
1. Nested directory filtering - Directories can now be ignored at any level in the project structure
2. Gitignore-style pattern matching - Patterns like `**/venv` can be used to ignore all `venv` directories regardless of their location

For the described case, either of these approaches can be applied:
```json
{
  "fileTreeExtractor.ignoredItems": ["venv"]
}
```
or
```json
{
  "fileTreeExtractor.ignoredItems": ["**/venv"]
}
```


The new functionality can be accessed by updating to the latest version. Any questions or issues with the new behaviour can be reported in the comments. Thank you!

**Comment by Bit-Blazer** [comment]
Thank you for the quick resolution and additional improvement! 

I’ve updated to the latest version and confirmed that it works perfectly as intended.  

Keep up the great work! 😊
