### ISSUE TITLE
`Error copying file tree: Failed to load gitignore` when copying from a folder containing multiple projects with their own `.gitignore` files

### ISSUE THREAD

**Issue by Bit-Blazer** [fuzionix/vscode-file-tree#3]
### `Error copying file tree: Failed to load gitignore` when copying from a folder containing multiple projects with their own `.gitignore` files

---

**Prerequisites**:  
The issue occurs when the `fileTreeExtractor.ignoredBy` setting is set to either `"gitignore"` or `"both"`. This setting determines how the extension handles files and folders to be ignored when generating the file tree structure.

Currently, when the setting is `"both"`, it works as an **AND** operation, meaning both the `.gitignore` file and `ignoredItems` must exist for the extension to combine the exclusions.

---

**Issue Description**:  
Let’s say I open a root folder (`company-name`) that does **not** have its own `.gitignore` file, but contains multiple subdirectories (`project1`, `project2`, `project3`), each of which has its own `.gitignore` file. When attempting to copy the file tree from the main folder (`company-name`) or any of the subdirectories (`project1`, `project2`, `project3`), I encounter the following error:  
`Error copying file tree: Failed to load gitignore`.  
This error is resolved only when I open one of the subdirectories that directly contains a `.gitignore` file as the root folder in VS Code.

---

**Sample Directory Structure**:

```
company-name/
├── project1/
│   ├── .gitignore
│   ├── src/
│   └── README.md
├── project2/
│   ├── .gitignore
│   ├── src/
│   └── README.md
├── project3/
│   ├── .gitignore
│   ├── src/
│   └── README.md
└── README.md
```

---

**Expected Behavior**:  
When copying the file tree from the **main directory `company-name`**, the extension should respect the `.gitignore` files inside **each subdirectory** (e.g., `project1`, `project2`, `project3`).

- If there are multiple `.gitignore` files in different subdirectories, the extension should correctly apply the rules of each `.gitignore` to its corresponding directory when copying the file tree.
- If the `fileTreeExtractor.ignoredBy` is set to `"both"`, the extension should work as an **OR** operation. This means it should respect **either** the `.gitignore` or `ignoredItems` settings (or both). If one of them is missing, the extension should still function correctly without throwing errors or excluding files unnecessarily.

Once this is resolved, copying the file tree should **work fine** and exclude the appropriate files based on the `.gitignore` settings in each subdirectory. The `"both"` option should not require both `.gitignore` and `ignoredItems` to be present.

---

**Actual Behavior**:  
Currently, the extension does not respect the `.gitignore` files within subdirectories when copying the file tree from a folder that itself does not have a `.gitignore` file. The error `Error copying file tree: Failed to load gitignore` occurs instead.  
Additionally, when `fileTreeExtractor.ignoredBy` is set to `"both"`, the extension checks for **both** `.gitignore` and `ignoredItems` and combines the exclusions, working as an **AND** operation. This leads to errors when either one is missing.

---

**Workaround**:  
Ensure that a `.gitignore` file exists in the root directory (or the directory from which you're trying to copy the file tree). If the `.gitignore` file is missing or not set up, the `fileTreeExtractor.ignoredBy` setting will not work as expected.

---

**Environment**:

- **VS Code Version**: 1.95.3  
- **File Tree Extractor Version**: v1.0.2  
- **Operating System**: Windows 11

**Comment by fuzionix** [comment]
The issue has been resolved in the latest version.

The extension now recursively searches for the nearest .gitignore file starting from the current directory up to the workspace root. However, notice that only the first found `.gitignore` file will be used. The extension won't merge multiple `.gitignore` files from different levels.

**Future Improvements to Consider**
- Support for merging multiple .gitignore files from different directory levels
- Add configuration option to control .gitignore inheritance behavior
- Cache .gitignore locations to improve performance
