### ISSUE TITLE
[Request] Option to ignore files

### ISSUE THREAD

**Issue by mubaidr** [fuzionix/vscode-file-tree#4]
Can we have option to ignore files and only list directories?

**Comment by fuzionix** [comment]
The feature has been added to the latest version.

The `fileTreeExtractor.directoryOnly` setting now supports the directory-only option without files. It is accessible via VSCode settings or settings.json. Use `"fileTreeExtractor.directoryOnly": true` to enable.

Any questions or issues with the new feature can be reported in the comments. Thank you!
